[packages.darwin.core]
"Git" = { source = "brew", package = "git", url = "https://git-scm.com" }
"curl" = { source = "brew", package = "curl", url = "https://curl.se" }
"Wget" = { source = "brew", package = "wget", url = "https://www.gnu.org/software/wget" }
"tree" = { source = "brew", package = "tree", url = "https://oldmanprogrammer.net/source.php?dir=projects/tree" }
"htop" = { source = "brew", package = "htop", url = "https://htop.dev" }
"Coreutils" = { source = "brew", package = "coreutils", url = "https://www.gnu.org/software/coreutils" }

[packages.darwin.browser]
"LibreWolf" = { source = "cask", package = "librewolf", url = "https://librewolf.net" }

[packages.darwin.media]
"VLC" = { source = "cask", package = "vlc", url = "https://www.videolan.org/vlc" }

[packages.darwin.gaming]
"Steam" = { source = "cask", package = "steam", url = "https://store.steampowered.com" }
"Jagex Launcher" = { source = "cask", package = "jagex", url = "https://www.jagex.com/launcher" }
"RuneLite" = { source = "cask", package = "runelite", url = "https://runelite.net" }

[packages.darwin.security]
"Bitwarden" = { source = "cask", package = "bitwarden", url = "https://bitwarden.com" }
"Bitwarden CLI" = { source = "brew", package = "bitwarden-cli", url = "https://bitwarden.com" }
