[packages.linux.core]
"Git" = { source = "pacman", package = "git", url = "https://git-scm.com" }
"curl" = { source = "pacman", package = "curl", url = "https://curl.se" }
"Wget" = { source = "pacman", package = "wget", url = "https://www.gnu.org/software/wget" }
"tree" = { source = "pacman", package = "tree", url = "https://oldmanprogrammer.net/source.php?dir=projects/tree" }
"htop" = { source = "pacman", package = "htop", url = "https://htop.dev" }

[packages.linux.browser]
"LibreWolf" = { source = "aur", package = "librewolf", url = "https://librewolf.net" }

[packages.linux.media]
"VLC" = { source = "pacman", package = "vlc", url = "https://www.videolan.org/vlc" }

[packages.linux.gaming]
"Steam" = { source = "pacman", package = "steam", url = "https://store.steampowered.com" }
"Bolt Launcher" = { source = "aur", package = "bolt-launcher", url = "https://adamcake.com/bolt" }
"RuneLite" = { source = "aur", package = "runelite", url = "https://runelite.net" }

[packages.linux.security]
"Bitwarden" = { source = "pacman", package = "bitwarden", url = "https://bitwarden.com" }
"Bitwarden CLI" = { source = "pacman", package = "bitwarden-cli", url = "https://bitwarden.com" }
