[packages.windows.browser]
LibreWolf = { source = "winget", package = "LibreWolf.LibreWolf", url = "https://librewolf.net" }

[packages.windows.security]
"Bitwarden CLI" = { source = "winget", package = "Bitwarden.CLI", url = "https://bitwarden.com" }
